### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Anyeos** [fkunn1326/openpose-editor#128]
**Describe the bug**
Drop an error message when starting webui.sh

**To Reproduce**
1. Start webui.sh

**Expected behavior**
No error message

**Environment**
 - OS: Ubuntu 20.04
 - Browser Firefox but I dont need to open the web interface the error is at startup of script.

**Additional context**
```
Error loading script: openpose_editor.py
Traceback (most recent call last):
  File "modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py", line 19, in <module>
    file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
TypeError: 'type' object is not subscriptable
```

**Comment by fkunn1326** [comment]
Maybe you are submitting issue to the wrong repository.
You should post it in https://github.com/nonnonstop/sd-webui-3d-open-pose-editor
