### ISSUE TITLE
OpenPose editor  txt2img and img2img  error message

### ISSUE THREAD

**Issue by ceo7188** [fkunn1326/openpose-editor#61]
After adjusting the human skeleton in the OpenPose editor, clicking on "txt2img" to transfer the image to ControlNet and selecting "none" for preprocessing, the image cannot be generated and an error is reported in the console. However, adding the skeleton image manually from ControlNet allows for successful generation of images. It seems that there is a problem with the transfer of images from OpenPose to ControlNet, and no images can be generated thereafter. Disabling the ControlNet function does not solve the problem, and the only solution is to refresh the page with F5 to restore normal functionality. I can confirm that the ControlNet function is working properly and that both manual drawing and importing of skeletons can be used to complete the drawing. The problem only occurs when using the OpenPose editor's txt2img and img2img functions.

=============================================
Console error message：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\AI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\AI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\components.py", line 1830, in preprocess
    ff.run()
  File "E:\AI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\ffmpy.py", line 98, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffmpeg' not found

==========================================

**Comment by caretaker0815** [comment]
I have the same problem

**Comment by jhskrt** [comment]
same problem

Traceback (most recent call last):
  File "D:\程\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\程\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\程\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\程\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1830, in preprocess
    ff.run()
  File "D:\程\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\ffmpy.py", line 98, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffmpeg' not found

**Comment by batblz** [comment]
I have this problem too.

**Comment by pzImmortal** [comment]
same problem

**Comment by MancV21** [comment]
Same thing here.

**Comment by troublemakerMibu** [comment]
same problem too

**Comment by GalaxyTimeMachine** [comment]
Me too

**Comment by MancV21** [comment]
There's a pull request to fix this, hopefully it'll be merged soon.
