### ISSUE TITLE
Is the OpenPose Editor not working? No response after installation.

### ISSUE THREAD

**Issue by heichang** [fkunn1326/openpose-editor#72]
Is the OpenPose Editor not working? No response after installation.

I do all thing about how to install , Extensionsshow out "openpose-edit" is exist, but there is no any page call OpenPose Editor, so I can't use it

thx for reading

**Comment by fkunn1326** [comment]
Please tell me more about the situation

**Comment by samuelykc** [comment]
Hi. ~13 hrs ago, I was installing OpenPose for the first time and encountered the same issue.

I am afraid there is not much details to mention:
Installation succeed.
Reload UI, tab not showing up.
Checked the setting page to look for anything relevant but nothing.
Ensured the extension was installed (from the "Extensions" tab & from my file directory), disabled & enabled it, still nothing.
Restart SD, nothing.
Revert SD to a revision a few days earlier, nothing.
Reinstall OpenPose, still nothing.

To conclude, it's really simply nothing shown up, nothing I could interact with...

**Comment by heichang** [comment]
Same as [samuelykc](https://github.com/samuelykc) said : Nothing.

Nothing happen or add after install.
Im sure Follow the step of install,but no matter how I Restart SD, 
Nothing come out .

**Comment by heichang** [comment]
> Please tell me more about the situation

Same as samuelykc said : Nothing.

Nothing happen or add after install.
Im sure Follow the step of install,but no matter how I Restart SD,
Nothing come out .

**Comment by fkunn1326** [comment]
Do you see any errors in the terminal?

**Comment by samuelykc** [comment]
> Do you see any errors in the terminal?

Oh, I think I've got something:
`Error executing callback ui_tabs_callback for D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py
Traceback (most recent call last):
  File "D:\Users\(username)\Documents\GitHub\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\Users\(username)\Documents\GitHub\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 76, in on_ui_tabs
    select_target_index = gr.Dropdown([str(i) for i in range(opts.control_net_max_models_num)], label="Send to", value="0", interactive=True, visible=(opts.control_net_max_models_num > 1))
  File "D:\Users\(username)\Documents\GitHub\stable-diffusion-webui\modules\shared.py", line 552, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'control_net_max_models_num'`

**Comment by fkunn1326** [comment]
I pushed the fix. please update and try again.

**Comment by samuelykc** [comment]
Thanks for the quick fix!

Just updated and applied the changes. I am afraid that there may be some syntax error in the script. Below is the console output I've got after update:
```
Restarting UI...
Error loading script: main.py
Traceback (most recent call last):
  File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 77
    if (hasattr(opts, 'control_net_max_models_num'):
                                                   ^
SyntaxError: invalid syntax
```

お手間を取らせて申し訳ございません。
引き続き宜しくお願い致します。🙇🏻‍♂️

**Comment by luoyeETH** [comment]
The new version seems to have the same issue

**Comment by jokker87** [comment]
There's a parenthese too much in that line of code.

**Comment by louishane** [comment]
> 

Updated OpenPoser and then the same problem. OpenPoser tab is gone. Reinstall can't fix it.

**Comment by louishane** [comment]
> Thanks for the quick fix!
> 
> Just updated and applied the changes. I am afraid that there may be some syntax error in the script. Below is the console output I've got after update:
> 
> ```
> Restarting UI...
> Error loading script: main.py
> Traceback (most recent call last):
>   File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 1017, in get_code
>   File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\Users\Samuel\Documents\GitHub\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 77
>     if (hasattr(opts, 'control_net_max_models_num'):
>                                                    ^
> SyntaxError: invalid syntax
> ```
> Updated OpenPoser and then the same problem. OpenPoser tab is gone. Reinstall can't fix it.
> お手間を取らせて申し訳ございません。 引き続き宜しくお願い致します。🙇🏻‍♂️

**Comment by RoguePilot001** [comment]
There's an extra open bracket in line 77 of main.py
Delete the ( before hasattr.

**Comment by EriIaz** [comment]
> There's an extra open bracket in line 77 of main.py Delete the ( before hasattr.

can confirm, removing the bracket fixes the issue

**Comment by Shmitter67** [comment]
Thanks @RoguePilot001 and @EriIaz , made that change and it fixed it for me

**Comment by Shmitter67** [comment]
Actually adding onto this thread, the tab works and I can make the rigging model all fine and dandy. But the generation completely ignores the pose prompt. Like 100% ignores, not even trying at all. Control Net is enabled, I've messed with various settings but the pose input on ControlNet with the model set to openpose (no preprocessor) and the pose is have no effect on the output. Anyone else having issues? Image below
![image](https://user-images.githubusercontent.com/69094185/224805651-59a8e307-f2bc-41bb-92d8-ac4d245b12fd.png)

**Comment by fkunn1326** [comment]
Fixed in https://github.com/fkunn1326/openpose-editor/commit/11e284531e2ccc0563176df194fe64847a1d9664
