### ISSUE TITLE
[Bug] Error loading script: main.py

### ISSUE THREAD

**Issue by Atlas-Diffusion** [fkunn1326/openpose-editor#78]
**Describe the bug**
Got this after the latest AUTO1111 webui git pull

**To Reproduce**
Just load the latest webui version with this extension

Error loading script: main.py
Traceback (most recent call last):
  File "C:\sd\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\sd\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd\extensions\openpose-editor\scripts\main.py", line 77
    if (hasattr(opts, 'control_net_max_models_num'):
                                                   ^
SyntaxError: invalid syntax

**Environment**
 - OS: Windows 11

**Comment by Atlas-Diffusion** [comment]
Found issue

In openpose-editor\scripts\main.py, line 77 has a bug.

Original (the bug one):
if (hasattr(opts, 'control_net_max_models_num'):

Fixed:
if (hasattr(opts, 'control_net_max_models_num')):

Yes. I add a ')' to fix it.

**Comment by Alchete** [comment]
Same.  Apparently merging fixes without trying them first.  🤦‍♂️

**Comment by nccncourage** [comment]
To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
Restarting UI...
Error loading script: main.py
Traceback (most recent call last):
  File "L:\AI ORGINAL\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "L:\AI ORGINAL\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\AI ORGINAL\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 77
    if (hasattr(opts, 'control_net_max_models_num'):
                                                   ^
SyntaxError: invalid syntax

same with u , and i fixed as ur adivice thx.

**Comment by fkunn1326** [comment]
Fixed in https://github.com/fkunn1326/openpose-editor/commit/11e284531e2ccc0563176df194fe64847a1d9664
