### ISSUE TITLE
New Install Not working Even after editing line 77 of main.py

### ISSUE THREAD

**Issue by AnsuzJeran** [fkunn1326/openpose-editor#80]
**Describe the bug**
Installing the extension for the first time doenst work even after edit fix

**To Reproduce**
Fresh install get first error of Line 77
Edit Line 77
Extension not working at all

**Expected behavior**
Extension working on AUTOMATIC111

**Environment**
 - OS: W10
 - Mozilla 110.0.1

**Additional context**
I did the fix of editing line 77 of main.py
Using Fix:

Original (the bug one):
if (hasattr(opts, 'control_net_max_models_num'):
Fixed:
if (hasattr(opts, 'control_net_max_models_num')):

New Error Appears:

Error loading script: main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 14, in <module>
    from scripts.openpose.body import Body
ModuleNotFoundError: No module named 'scripts.openpose'

**Comment by fkunn1326** [comment]
I just fixed it. Please update and check

**Comment by AnsuzJeran** [comment]
Thanks for the fix

**Comment by Bodzijun** [comment]
and today...
\extensions\openpose-editor\scripts\main.py", line 89
SyntaxError: invalid syntax
