### ISSUE TITLE
RuntimeError happened after force relaunch webui

### ISSUE THREAD

**Issue by AnalQueen** [fkunn1326/openpose-editor#91]
**Describe the bug**
I was using openpose-editor for the first time today, and i was using 'detect from image', i didn't notice it was loading and closed webui, after relaunch, the error accured.

I deleted the extension and reinstalled again, the error still shows up.

**Expected behavior**
I think it's because of my force relaunch, some file was corrupt, but i don't know which is it.

**Screenshots**

**Environment**
 - OS: windows 11
 - Browser chrome

**Additional context**
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\novelai-webui-aki-v3\extensions\openpose-editor\scripts\main.py", line 102, in estimate
    body_estimation = Body(model_path)
  File "D:\novelai-webui-aki-v3\extensions\openpose-editor\scripts\openpose\body.py", line 21, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "D:\novelai-webui-aki-v3\extensions\sd_smartprocess\reallysafe.py", line 117, in load
    return load_with_extra(filename, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\extensions\sd_smartprocess\reallysafe.py", line 164, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 3320738 more bytes. The file might be corrupted.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by fkunn1326** [comment]
Try disabling sd_smartprocess

**Comment by AnalQueen** [comment]
I disabled sd_smartprocess, still having errors

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\novelai-webui-aki-v3\extensions\openpose-editor\scripts\main.py", line 102, in estimate
    body_estimation = Body(model_path)
  File "D:\novelai-webui-aki-v3\extensions\openpose-editor\scripts\openpose\body.py", line 21, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "D:\novelai-webui-aki-v3\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 3320738 more bytes. The file might be corrupted.

**Comment by AnalQueen** [comment]
reinstalled everything now it works

**Comment by AnalQueen** [comment]
reinstalled everything now it works
